"""Quantum-inspired optimization over rejuvenation intervention stacks."""
from __future__ import annotations

import numpy as np
from typing import Any, Dict, List

from quantum_enhanced_ea import QuantumEnhancedEvolutionaryAlgorithm
from age_reversal_module import (
    AgeReversalResearchEngine,
    RejuvenationIntervention,
    RejuvenationHypothesis,
)


class RejuvenationQuantumOptimizer:
    """Wrap QuantumEnhancedEvolutionaryAlgorithm to search intervention subsets."""

    def __init__(
        self,
        age_engine: AgeReversalResearchEngine,
        candidate_interventions: List[RejuvenationIntervention],
    ):
        self.age_engine = age_engine
        self.candidate_interventions = candidate_interventions

    def _decode_chromosome(self, chrom: np.ndarray) -> List[RejuvenationIntervention]:
        """Map a chromosome vector in [0,1]^N to a subset of interventions."""
        selected: List[RejuvenationIntervention] = []
        for gene, intervention in zip(chrom, self.candidate_interventions):
            if gene > 0.5:
                selected.append(intervention)
        return selected

    def optimize(
        self,
        population_size: int = 32,
        num_generations: int = 20,
        weights: Dict[str, float] | None = None,
    ) -> Dict[str, Any]:
        dim = len(self.candidate_interventions)
        qea = QuantumEnhancedEvolutionaryAlgorithm(
            population_size=population_size,
            num_generations=num_generations,
        )

        # Override population dimension to match intervention candidates
        qea.population = np.random.rand(population_size, dim)

        best_score = -1e9
        best_hypothesis_id: str | None = None

        for gen in range(num_generations):
            scores = []
            for chrom in qea.population:
                selected = self._decode_chromosome(chrom)
                if not selected:
                    scores.append(-1e6)
                    continue

                hypothesis_id = f"qea_gen{gen}_cand{len(self.age_engine.hypotheses) + 1}"
                hypothesis = RejuvenationHypothesis(
                    id=hypothesis_id,
                    interventions=selected,
                    rationale="Auto-generated by quantum-inspired EA",
                )
                self.age_engine.register_hypothesis(hypothesis)

                score = self.age_engine.score_hypothesis_for_optimization(
                    hypothesis_id,
                    weights,
                )
                scores.append(score)

                if score > best_score:
                    best_score = score
                    best_hypothesis_id = hypothesis_id

            qea.evolve(np.array(scores))

        return {
            "best_score": best_score,
            "best_hypothesis_id": best_hypothesis_id,
            "summary": self.age_engine.simple_consistency_check(best_hypothesis_id)
            if best_hypothesis_id
            else None,
        }
